### ISSUE TITLE
CodeWindow Scrolling doesn't work properly

### ISSUE THREAD

**Issue by mblecker** [uni-bremen-agst/SEE#428]
If you scroll inside the Code-Window the Cursor scrolls outside the Code-Window.
Or if you have marked a line, it will move upwards or downwards
If you try to select a line afterwards, the cursor is not shown on the correct spot.
Also, the mouse wheel only works for scrolling up

**Comment by falko17** [comment]
No longer relevant as editing capabilities have been removed.
