### ISSUE TITLE
Setup CI for static code analysis with Axivion Suite version 7.6

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#619]
We want to check our code with Axivion Suite version 7.6.
We used an earlier version of it. Unfortunately, the installation was deleted. We need to revive it and possibly make adjustments as part of a migration to version 7.6.

**Comment by falko17** [comment]
@koschke Is this resolved now, since Axivion Suite analyses are integrated into the CI again?

**Comment by koschke** [comment]
It is resolved. I am closing it.
