### ISSUE TITLE
Integrate Embedded Browser

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#654]
We want our users to browse the Internet within the game. The plugin Embedded Browser provides a browser to exactly do that. It should be integrated.

**Comment by koschke** [comment]
@lilSander @TimDinh-hub @Omidious A new branch `654-embedded-browser` exists where the [Embedded Browser plugin](https://zenfulcrum.com/browser) is checked in. For additional information on this plugin visit [this website](https://zenfulcrum.com/browser/docs/Readme.html). The plugin was bought from [here](https://assetstore.unity.com/packages/tools/gui/embedded-browser-55459).

**Comment by lilSander** [comment]
@TimDinh-hub @Omidious ich hab mal einen Discord-Server aufgemacht, falls wir die Tage oder so was besprechen müssen: https://discord.gg/Xzn3X5cM
