### ISSUE TITLE
Avoid player leaving the scene through walls/floor

### ISSUE THREAD

**Issue by SarahAugustinowski** [uni-bremen-agst/SEE#694]
At the moment its possible for the player/avatar to leave the "office"-scene by going through the walls/floor. Going through the table is fine for better view on the tables and for faster position changes but going through walls feels a little bit awkward.

**Comment by koschke** [comment]
What do you mean? Of course, a player should be able to leave the game. Or do you mean that an avatar should not be able to walk through the walls of the office? Your issue should be clearer about that.

**Comment by SarahAugustinowski** [comment]
> What do you mean? Of course, a player should be able to leave the game. Or do you mean that an avatar should not be able to walk through the walls of the office? Your issue should be clearer about that.

Sorry! I meant going through walls and the floor. I edited the description and title, hopefully it’s more clear now.
