### ISSUE TITLE
Window to show metrics

### ISSUE THREAD

**Issue by TimDinh-hub** [uni-bremen-agst/SEE#700]
Implements a window where the metrics will be shown. It involves additional features for the metrics window to improve usability. The primary objectives are to integrate a search function and enhance the visual appeal of the window.

**Comment by koschke** [comment]
This description is a bit short. Could you elaborate it a bit? 

By the way, you may be inspired by the key-binding panel that is part of the settings menu. @lilSander is an expert on this.
