### ISSUE TITLE
Loading spinner loops forever when the reflexion analysis creates new edges.

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#722]
The `EdgeMeshScheduler `shows a `LoadingSpinner `upon the `OnNext `event somehow triggered by the reflexion analysis.
This `LoadingSpinner `does not disappear again. Somehow, the closing of it is missing.

**Comment by falko17** [comment]
I cannot reproduce this issue, I'll assume it has been fixed in the meantime.
