### ISSUE TITLE
Let ClientActionNetwork use async via UniTask instead of using co-routines

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#749]
Class `SEE.Net.ClientActionNetwork` makes heavy use of coroutines to deal with asynchronous code.  We should consider refactoring it to use async via UniTask instead, to make it consistent with the rest of SEE and gain improved efficiency. This would also simplify some code (e.g., in GetAllData).

**Comment by tinxx** [comment]
Solved by #753.
