### ISSUE TITLE
MissingReferenceException in HelpMenu

### ISSUE THREAD

**Issue by Cyclone1337** [uni-bremen-agst/SEE#791]
There is a missing reference exception bug with the HelpMenu.
The playback of the first video works, but when a second video is supposed to be started afterward, a `MissingReferenceException` occurs, indicating that no `VideoPlayer` is present. (see the video below)

> MissingReferenceException: The object of type 'VideoPlayer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
SEE.UI.HelpSystem.HelpSystemEntry.UpdateDesktop () (at Assets/SEE/UI/HelpSystem/HelpSystemEntry.cs:171)
SEE.UI.PlatformDependentComponent.Update () (at Assets/SEE/UI/PlatformDependentComponent.cs:107)

Additionally, the video for `DrawFree` is missing.
However, this is not relevent, as `DrawFree` is intended to be removed. `DrawFree` is only visible to the executing user and serveres no purpose.
> WindowsMediaFoundation received empty file C:/Repo/SEE/Assets/StreamingAssets\HelpSystem/Videos/DrawFreeRoom.mp4

https://github.com/user-attachments/assets/ec145243-93ad-4920-bf9e-e66196ba48a9

**Comment by SarahAugustinowski** [comment]
I think the problem is caused by changes in d589ecb73ca3b54b5b524d938990a2c02466192b. Reverting this fixed it locally for me. Maybe @koschke should look here too, before I change it back to old state.

The path for DrawFree is corrected.

**Comment by koschke** [comment]
I fixed this problem.
